### ISSUE TITLE
Test project card -- new task template

### ISSUE THREAD

**Issue by s8sun** [cse110-fa21-group17/cse110-fa21-group17#10]
`This is a test` 
# Task name
Assigned team: front end
## Task descriptions:
- Implement landing page `landing.html`
- Use Figma as reference, implement all features shown in Figma
- [ ] Place to insert recipe card
- [ ] Top recipe and user created recipe
- [ ] Logo and place to insert links (logo should link back to home page)
- [ ] Search bar
- [ ] Buttons to link to other pages (top right corner)
- [ ] Profile pic, and when clicked on, it should generate a box (see comments)
- Check comments in case all new designs are not reflected

## Requirements:
1. Work on `html` and `css` components
2. After done, validate using W3C https://validator.w3.org/
