### ISSUE TITLE
Recipe card template

### ISSUE THREAD

**Issue by s8sun** [cse110-fa21-group17/cse110-fa21-group17#23]
# Implement recipe card template
Assigned team: front end 
## Task descriptions:
- Implement landing page `recipeCardTemplate.html`
- Use Figma as reference, implement all necessary elements of an recipe card
- [ ] Each html element in this card template should have `class name` or `id` so they can be selected easily
- [ ] Classes or html elements in the template should contain appropriate names
- [ ] Use filler data / dummy data in the template so other developers knows which fields should be substituted. 
- [ ] Think about user's interaction with the recipe card. Reserve html fields to allow next step `js` implementation (will the card change or show any buttons (such as like button) when mouse is hovered over the card? if it shows a "liked" button, reserve a clickable button field on the card)

## Requirements:
1. Create feature branch
2. Work on `html` and `css` components
3. After done, validate using W3C https://validator.w3.org/

**Comment by jkwok626** [comment]
HTML: 
```
<a href="#"> <!--Insert link to recipe page-->
    <div class="recipeCard">
        <div class="cardText">
            <p class="recipeTitle">Pumpkin Pie</p> 
            <p class="card-tags">Easy To Make | Snack Time</p>
            <p class="card-details">1 Hour | 8 Ingredients</p>
        </div>
        <img src="https://joyfoodsunshine.com/wp-content/uploads/2018/02/best-chocolate-chip-cookies-recipe-1.jpg"
        class="cardImage">
    </div>
</a>
```

CSS:
```
@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');

.recipeCard {
    position: relative;
    text-align: left;
    color: white;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);
    border-radius: 0.8em;
    margin-left: 10px;
    margin-right: 10px;
    background-image: linear-gradient(to bottom, rgba(255,255,255,0), rgba(255,255,255,0), rgba(0,0,0,0.8));
    width: 400px;
    height: 290px;
    font-family: 'Nunito', sans-serif;
}

.recipeCard:first-child{
    margin-left:0px;
}

.recipeCard:hover{
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
    border-radius: 0.8em;
}

.card-text{
  color: white;
  text-shadow: -2px 4px 0 rgba(0,0,0,0.3);
}

.cardImage {
    border-radius: 0.8em; 
    position: relative;
    z-index: -1;
    width: 400px;
    height: 290px;
    object-fit:cover; 
}

.cardText {
    position: absolute;
    bottom: 0.5em;
    left: 1em;
}

.card-tags{
    margin:0px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
    font-weight: 400;
}

.card-details{
    margin-top:10px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
    font-weight: 400;
}

.recipeTitle {
    font-weight: 700;
    font-size:1.5em;    
    margin: 0px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
}
```
*This doesn't have the bookmark icon yet
![image](https://user-images.githubusercontent.com/68207336/142706578-00428e57-27ba-4b6b-9dae-610e9f88bb47.png)

**Comment by jkwok626** [comment]
**Updated version with nonfunctional bookmark icon**
This icon doesn't do anything right now and I don't think we need it for the MVP.

HTML:
```
<a href="#"> <!--Insert link to recipe page-->
    <div class="recipeCard">
       <div class="bookmark-icon">
           <i class="bi bi-bookmark" style="font-size: 2em;"></i>
        </div>
        <div class="cardText">
            <p class="recipeTitle">Pumpkin Pie</p> 
            <p class="card-tags">Easy To Make | Snack Time</p>
            <p class="card-details">1 Hour | 8 Ingredients</p>
        </div>
        <img src="https://joyfoodsunshine.com/wp-content/uploads/2018/02/best-chocolate-chip-cookies-recipe-1.jpg"
        class="cardImage">
    </div>
</a>
```

CSS:
```
@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@700;800;900&display=swap');

.recipeCard {
    position: relative;
    text-align: left;
    color: white;
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    transition: all 0.3s cubic-bezier(.25,.8,.25,1);
    border-radius: 0.8em;
    margin-left: 10px;
    margin-right: 10px;
    background-image: linear-gradient(to bottom, rgba(255,255,255,0), rgba(255,255,255,0), rgba(0,0,0,0.8));
    width: 400px;
    height: 290px;
    font-family: 'Nunito', sans-serif;
}

.recipeCard:first-child{
    margin-left:0px;
}

.recipeCard:hover{
    box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
    border-radius: 0.8em;
}

.card-text{
  color: white;
  text-shadow: -2px 4px 0 rgba(0,0,0,0.3);
}

.cardImage {
    border-radius: 0.8em; 
    position: relative;
    z-index: -1;
    width: 400px;
    height: 290px;
    object-fit:cover; 
}

.cardText {
    position: absolute;
    bottom: 0.5em;
    left: 1em;
}

.card-tags{
    margin:0px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
    font-weight: 400;
}

.card-details{
    margin-top:10px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
    font-weight: 400;
}

.recipeTitle {
    font-weight: 700;
    font-size:1.5em;    
    margin: 0px;
    text-shadow: 2px 4px 3px rgba(0,0,0,0.3);
}

.bookmark-icon {
  position: absolute;
  top: 0.5em;
  right: 1em;
}
```

**Comment by jkwok626** [comment]
**Added JS to Change Fill of Bookmark Icon**
Please check out this Codepen: [https://codepen.io/jkwok626/pen/mdMZKBL](url)

This hasn't been added to the landing page yet and it needs to be connected to the backend (I left some comments in the Codepen).
