### ISSUE TITLE
Implement recipe page

### ISSUE THREAD

**Issue by s8sun** [cse110-fa21-group17/cse110-fa21-group17#24]
# Implement recipe page
Assigned team: front end
## Task descriptions:
- Implement `recipePage.html` and some js for timer and SpeechSynthesizer
- Use Figma as reference, implement all features shown in Figma
- [ ] Grid components 
- [ ] Test different design choices -- how would you design the page for different browser / client
- [ ] Test on different screen size, (on desktop and mobile)
- [ ] **Include the search bar, and the buttons on top of every single page** (may need to collaborate with landing page team)
- [ ] A button to click on for the timer
- [ ] A button to click on for `SpeechSynthesizer`

## Requirements:
1. Create feature branch
2. Work on `html` and `css` and some front end `js` components
3. After done, validate using W3C https://validator.w3.org/
