### ISSUE TITLE
Implement cook book pages: main page and add/edit page

### ISSUE THREAD

**Issue by s8sun** [cse110-fa21-group17/cse110-fa21-group17#25]
# Implement cook book pages: main page and add/edit page
Assigned team: front end
**Discussion needed! Let's revisit Figma for design choice on Thursday's 11/18 meeting. Let's discuss:**
1. Do we want the liked recipe and user created recipe separate on two pages? Or just in one page called `My recipes` with two rows? 
## Task descriptions:
- Implement `myCookBook.html` 
- Use Figma as reference, implement all features shown in Figma
- [ ] Place to insert recipe card
- [ ] Include the search bar, and the buttons on top of every single page (may need to collaborate with landing page team)

- Implement `addEditRecipe.html`
- [ ] In edit view, you can delete the entire recipe
- [ ] In edit view, you can delete or edit a specific field (steps, ingredients, nutrition data)
- [ ] If the above is implemented correctly, adding a new recipe should be the same as editing (inserting to) an empty recipe. 
- [ ] In edit view, you can insert at any position
- [ ] Include the search bar, and the buttons on top of every single page (may need to collaborate with landing page team)

## Metrics of success:
1. Complete `html` and `css` and 'js' components
2. In `addEditRecipe` page, there may be multiple cases you need to consider. Makes sure you consider all possible use cases.
3. In `addEditRecipe` page, you may want to create in-page window (**Let's also discuss this in the meeting. During Monday's discussion we saw one group doing that, (they have a orange / pinkish UI design and they demoed their edit recipe page). I forgot which group it was exactly. @ThomasLiARDJAVA @rcherukuru2000  Do you guys remember?**)
3. After done, validate using W3C https://validator.w3.org/
